name: Build travel profiles (Admin-1)

on:
  workflow_dispatch:
    inputs:
      provider:
        description: 'Provider: worldclim or era5'
        required: false
        default: 'worldclim'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/travel_profiles/requirements.txt
      - name: Generate profiles
        env:
          PROVIDER: ${{ github.event.inputs.provider }}
        run: |
          cd tools/travel_profiles
          python build_profiles.py --provider ${PROVIDER:-worldclim} --out ../../wandermap/public/data/travel/profiles_admin1.json
      - name: Create PR with profiles
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: 'chore: add/update travel profiles JSON'
          title: 'Data: update travel climate profiles (Admin-1)'
          branch: scout/data-travel-profiles
          body: 'Automated update of profiles_admin1.json generated by workflow.'
